/**
 * @file omni_robot.h
 *
 * @brief This header file was generated by cantools version 41.1.1 Sun Feb 22 22:25:55 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef OMNI_ROBOT_H
#define OMNI_ROBOT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define OMNI_ROBOT_MCU_STATUS_1_FRAME_ID (0x101u)
#define OMNI_ROBOT_MCU_STATUS_2_FRAME_ID (0x102u)
#define OMNI_ROBOT_MCU_STATUS_3_FRAME_ID (0x103u)
#define OMNI_ROBOT_MCU_STATUS_4_FRAME_ID (0x104u)
#define OMNI_ROBOT_R_PI_COMMAND_1_FRAME_ID (0x201u)
#define OMNI_ROBOT_R_PI_COMMAND_2_FRAME_ID (0x202u)
#define OMNI_ROBOT_R_PI_COMMAND_3_FRAME_ID (0x203u)
#define OMNI_ROBOT_R_PI_COMMAND_4_FRAME_ID (0x204u)

/* Frame lengths in bytes. */
#define OMNI_ROBOT_MCU_STATUS_1_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_2_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_3_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_4_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_1_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_2_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_3_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_4_LENGTH (8u)

/* Extended or standard frame types. */
#define OMNI_ROBOT_MCU_STATUS_1_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_2_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_3_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_4_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_1_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_2_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_3_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_4_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define OMNI_ROBOT_MCU_STATUS_1_NAME "MCU_Status_1"
#define OMNI_ROBOT_MCU_STATUS_2_NAME "MCU_Status_2"
#define OMNI_ROBOT_MCU_STATUS_3_NAME "MCU_Status_3"
#define OMNI_ROBOT_MCU_STATUS_4_NAME "MCU_Status_4"
#define OMNI_ROBOT_R_PI_COMMAND_1_NAME "RPi_Command_1"
#define OMNI_ROBOT_R_PI_COMMAND_2_NAME "RPi_Command_2"
#define OMNI_ROBOT_R_PI_COMMAND_3_NAME "RPi_Command_3"
#define OMNI_ROBOT_R_PI_COMMAND_4_NAME "RPi_Command_4"

/* Signal Names. */
#define OMNI_ROBOT_MCU_STATUS_1_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_1_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_1_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_1_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_2_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_2_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_2_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_2_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_3_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_3_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_3_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_3_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_4_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_4_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_4_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_4_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_R_PI_COMMAND_1_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_1_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_1_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_1_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_2_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_2_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_2_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_2_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_3_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_3_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_3_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_3_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_4_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_4_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_4_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_4_STOP_CMD_NAME "StopCmd"

/**
 * Signals in message MCU_Status_1.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_1_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_2.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_2_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_3.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_3_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_4.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_4_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message RPi_Command_1.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_1_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_2.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_2_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_3.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_3_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_4.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_4_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Pack message MCU_Status_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_1_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_1_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_1_unpack(
    struct omni_robot_mcu_status_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_1_init(struct omni_robot_mcu_status_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_1_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_1_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_1_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_1_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_2_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_2_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_2_unpack(
    struct omni_robot_mcu_status_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_2_init(struct omni_robot_mcu_status_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_2_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_2_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_2_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_2_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_3_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_3_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_3_unpack(
    struct omni_robot_mcu_status_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_3_init(struct omni_robot_mcu_status_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_3_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_3_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_3_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_3_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_4_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_4_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_4_unpack(
    struct omni_robot_mcu_status_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_4_init(struct omni_robot_mcu_status_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_4_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_4_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_4_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_4_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_1_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_1_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_1_unpack(
    struct omni_robot_r_pi_command_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_1_init(struct omni_robot_r_pi_command_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_1_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_1_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_1_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_1_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_2_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_2_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_2_unpack(
    struct omni_robot_r_pi_command_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_2_init(struct omni_robot_r_pi_command_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_2_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_2_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_2_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_2_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_3_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_3_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_3_unpack(
    struct omni_robot_r_pi_command_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_3_init(struct omni_robot_r_pi_command_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_3_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_3_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_3_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_3_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_4_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_4_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_4_unpack(
    struct omni_robot_r_pi_command_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_4_init(struct omni_robot_r_pi_command_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_4_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_4_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_4_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_4_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_stop_cmd_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
