/**
 * @file omni_robot.c
 *
 * @brief This source file was generated by cantools version 41.1.1 Sun Feb 22 22:25:55 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "omni_robot.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int omni_robot_mcu_status_1_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->joint_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->joint_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->joint_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->joint_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->joint_temp_c, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->torque_enabled, 0u, 0x01u);

    return (8);
}

int omni_robot_mcu_status_1_unpack(
    struct omni_robot_mcu_status_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->joint_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->joint_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->joint_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->joint_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->joint_temp_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->torque_enabled = unpack_right_shift_u8(src_p[5], 0u, 0x01u);

    return (0);
}

int omni_robot_mcu_status_1_init(struct omni_robot_mcu_status_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_mcu_status_1_t));

    return 0;
}

uint16_t omni_robot_mcu_status_1_joint_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_mcu_status_1_joint_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_mcu_status_1_joint_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_mcu_status_1_joint_voltage_m_v_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_mcu_status_1_joint_voltage_m_v_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_1_joint_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_mcu_status_1_joint_temp_c_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_1_joint_temp_c_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_1_joint_temp_c_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t omni_robot_mcu_status_1_torque_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_1_torque_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_1_torque_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_mcu_status_2_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->joint_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->joint_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->joint_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->joint_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->joint_temp_c, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->torque_enabled, 0u, 0x01u);

    return (8);
}

int omni_robot_mcu_status_2_unpack(
    struct omni_robot_mcu_status_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->joint_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->joint_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->joint_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->joint_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->joint_temp_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->torque_enabled = unpack_right_shift_u8(src_p[5], 0u, 0x01u);

    return (0);
}

int omni_robot_mcu_status_2_init(struct omni_robot_mcu_status_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_mcu_status_2_t));

    return 0;
}

uint16_t omni_robot_mcu_status_2_joint_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_mcu_status_2_joint_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_mcu_status_2_joint_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_mcu_status_2_joint_voltage_m_v_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_mcu_status_2_joint_voltage_m_v_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_2_joint_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_mcu_status_2_joint_temp_c_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_2_joint_temp_c_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_2_joint_temp_c_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t omni_robot_mcu_status_2_torque_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_2_torque_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_2_torque_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_mcu_status_3_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->joint_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->joint_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->joint_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->joint_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->joint_temp_c, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->torque_enabled, 0u, 0x01u);

    return (8);
}

int omni_robot_mcu_status_3_unpack(
    struct omni_robot_mcu_status_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->joint_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->joint_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->joint_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->joint_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->joint_temp_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->torque_enabled = unpack_right_shift_u8(src_p[5], 0u, 0x01u);

    return (0);
}

int omni_robot_mcu_status_3_init(struct omni_robot_mcu_status_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_mcu_status_3_t));

    return 0;
}

uint16_t omni_robot_mcu_status_3_joint_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_mcu_status_3_joint_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_mcu_status_3_joint_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_mcu_status_3_joint_voltage_m_v_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_mcu_status_3_joint_voltage_m_v_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_3_joint_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_mcu_status_3_joint_temp_c_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_3_joint_temp_c_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_3_joint_temp_c_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t omni_robot_mcu_status_3_torque_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_3_torque_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_3_torque_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_mcu_status_4_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->joint_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->joint_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->joint_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->joint_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->joint_temp_c, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->torque_enabled, 0u, 0x01u);

    return (8);
}

int omni_robot_mcu_status_4_unpack(
    struct omni_robot_mcu_status_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->joint_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->joint_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->joint_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->joint_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->joint_temp_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->torque_enabled = unpack_right_shift_u8(src_p[5], 0u, 0x01u);

    return (0);
}

int omni_robot_mcu_status_4_init(struct omni_robot_mcu_status_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_mcu_status_4_t));

    return 0;
}

uint16_t omni_robot_mcu_status_4_joint_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_mcu_status_4_joint_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_mcu_status_4_joint_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_mcu_status_4_joint_voltage_m_v_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_mcu_status_4_joint_voltage_m_v_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_4_joint_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_mcu_status_4_joint_temp_c_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_4_joint_temp_c_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_4_joint_temp_c_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t omni_robot_mcu_status_4_torque_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_mcu_status_4_torque_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_mcu_status_4_torque_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_r_pi_command_1_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->target_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->target_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->move_duration_ms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->move_duration_ms, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->torque_enable, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->stop_cmd, 1u, 0x02u);

    return (8);
}

int omni_robot_r_pi_command_1_unpack(
    struct omni_robot_r_pi_command_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->target_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->move_duration_ms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->move_duration_ms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_enable = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->stop_cmd = unpack_right_shift_u8(src_p[4], 1u, 0x02u);

    return (0);
}

int omni_robot_r_pi_command_1_init(struct omni_robot_r_pi_command_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_r_pi_command_1_t));

    return 0;
}

uint16_t omni_robot_r_pi_command_1_target_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_r_pi_command_1_target_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_r_pi_command_1_target_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_r_pi_command_1_move_duration_ms_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_r_pi_command_1_move_duration_ms_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_1_move_duration_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_r_pi_command_1_torque_enable_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_1_torque_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_1_torque_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omni_robot_r_pi_command_1_stop_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_1_stop_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_1_stop_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_r_pi_command_2_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->target_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->target_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->move_duration_ms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->move_duration_ms, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->torque_enable, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->stop_cmd, 1u, 0x02u);

    return (8);
}

int omni_robot_r_pi_command_2_unpack(
    struct omni_robot_r_pi_command_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->target_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->move_duration_ms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->move_duration_ms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_enable = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->stop_cmd = unpack_right_shift_u8(src_p[4], 1u, 0x02u);

    return (0);
}

int omni_robot_r_pi_command_2_init(struct omni_robot_r_pi_command_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_r_pi_command_2_t));

    return 0;
}

uint16_t omni_robot_r_pi_command_2_target_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_r_pi_command_2_target_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_r_pi_command_2_target_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_r_pi_command_2_move_duration_ms_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_r_pi_command_2_move_duration_ms_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_2_move_duration_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_r_pi_command_2_torque_enable_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_2_torque_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_2_torque_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omni_robot_r_pi_command_2_stop_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_2_stop_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_2_stop_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_r_pi_command_3_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->target_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->target_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->move_duration_ms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->move_duration_ms, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->torque_enable, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->stop_cmd, 1u, 0x02u);

    return (8);
}

int omni_robot_r_pi_command_3_unpack(
    struct omni_robot_r_pi_command_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->target_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->move_duration_ms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->move_duration_ms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_enable = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->stop_cmd = unpack_right_shift_u8(src_p[4], 1u, 0x02u);

    return (0);
}

int omni_robot_r_pi_command_3_init(struct omni_robot_r_pi_command_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_r_pi_command_3_t));

    return 0;
}

uint16_t omni_robot_r_pi_command_3_target_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_r_pi_command_3_target_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_r_pi_command_3_target_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_r_pi_command_3_move_duration_ms_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_r_pi_command_3_move_duration_ms_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_3_move_duration_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_r_pi_command_3_torque_enable_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_3_torque_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_3_torque_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omni_robot_r_pi_command_3_stop_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_3_stop_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_3_stop_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omni_robot_r_pi_command_4_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->target_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->target_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->move_duration_ms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->move_duration_ms, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->torque_enable, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->stop_cmd, 1u, 0x02u);

    return (8);
}

int omni_robot_r_pi_command_4_unpack(
    struct omni_robot_r_pi_command_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->target_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->move_duration_ms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->move_duration_ms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_enable = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->stop_cmd = unpack_right_shift_u8(src_p[4], 1u, 0x02u);

    return (0);
}

int omni_robot_r_pi_command_4_init(struct omni_robot_r_pi_command_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omni_robot_r_pi_command_4_t));

    return 0;
}

uint16_t omni_robot_r_pi_command_4_target_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omni_robot_r_pi_command_4_target_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omni_robot_r_pi_command_4_target_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint16_t omni_robot_r_pi_command_4_move_duration_ms_encode(double value)
{
    return (uint16_t)(value);
}

double omni_robot_r_pi_command_4_move_duration_ms_decode(uint16_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_4_move_duration_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t omni_robot_r_pi_command_4_torque_enable_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_4_torque_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_4_torque_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omni_robot_r_pi_command_4_stop_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double omni_robot_r_pi_command_4_stop_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool omni_robot_r_pi_command_4_stop_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
